import = [
"~/.config/alacritty/gruvbox-material.toml", 
"~/.config/alacritty/keybindings.toml"
]

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 14.0

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
opacity = 1
