[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 16.0

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
opacity = 1

[general]
import = [
"~/.config/alacritty/gruvbox-material.toml", 
"~/.config/alacritty/keybindings.toml"
]
