#!/usr/bin/env sh

yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          on				\
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.5           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  0             \
    bottom_padding               0             \
    left_padding                 0             \
    right_padding                0             \
    window_gap                   01             \
    layout                       bsp            \
    mouse_modifier               cmd             \
	mouse_action1				 resize			\

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Lara$" manage=off
yabai -m rule --add app="^java$" manage=off
